# Generated by Django 5.0.7 on 2024-07-11 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
                ('coin_sides', models.CharField(choices=[('Head', 'Head'), ('Tail', 'Tail')], max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Toss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
                ('toss_id', models.CharField(max_length=5)),
                ('staked_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('predicted_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tossApi.coinmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
                ('outcome', models.CharField(max_length=4)),
                ('toss_status', models.BooleanField(default=False)),
                ('toss', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tossApi.toss')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
